services:
  skinserver:
    container_name: skinserver
    volumes:
      - /root/skinserver:/app
    ports:
      - "8088:8088"
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped